namespace Source2Boost.App;

/// <summary>Сервис локализации RU/UK/EN с переключением на лету.</summary>
public static class Loc
{
    public static string Lang { get; private set; } = "ru";
    public static event Action? Changed;

    public static void Set(string lang)
    {
        if (lang == Lang) return;
        Lang = lang;
        Changed?.Invoke();
    }

    public static string T(string key) => _s.TryGetValue(key, out var v) ? v.For(Lang) : key;

    /// <summary>Славянское склонение по числу: one=1, few=2–4, many=5–0/11–14. En — one/many.</summary>
    public static string Plural(int n, string one, string few, string many)
    {
        if (Lang == "en") return n == 1 ? one : many;
        int nn = Math.Abs(n) % 100, n1 = nn % 10;
        if (nn is > 10 and < 20) return many;
        if (n1 == 1) return one;
        if (n1 is > 1 and < 5) return few;
        return many;
    }

    /// <summary>«21 твик» / «22 твика» / «25 твиков» (и UK/EN) — с правильным склонением.</summary>
    public static string Tweaks(int n)
    {
        var word = Lang switch
        {
            "uk" => Plural(n, "твік", "твіки", "твіків"),
            "en" => n == 1 ? "tweak" : "tweaks",
            _ => Plural(n, "твик", "твика", "твиков"),
        };
        return $"{n} {word}";
    }

    private readonly record struct S(string Ru, string Uk, string En)
    {
        public string For(string l) => l switch { "uk" => Uk, "en" => En, _ => Ru };
    }

    private static readonly Dictionary<string, S> _s = new()
    {
        ["brand.sub"]     = new("Оптимизатор CS2", "Оптимізатор CS2", "CS2 optimizer"),
        ["grp.main"]      = new("ОСНОВНОЕ", "ОСНОВНЕ", "MAIN"),
        ["grp.game"]      = new("ИГРА", "ГРА", "GAME"),
        ["nav.dash"]      = new("Обзор", "Огляд", "Overview"),
        ["nav.boost"]     = new("Оптимизация", "Оптимізація", "Optimize"),
        ["nav.tweaks"]    = new("Твики", "Твіки", "Tweaks"),
        ["nav.monitor"]   = new("Тест и прогноз", "Тест і прогноз", "Test & forecast"),
        ["nav.lab"]       = new("Лаборатория", "Лабораторія", "Lab"),
        ["nav.cs2"]       = new("Настройки CS2", "Налаштування CS2", "CS2 config"),
        ["nav.restore"]   = new("Откат", "Відкат", "Restore"),

        ["dash.title"]    = new("Обзор системы", "Огляд системи", "System overview"),
        ["dash.tagline"]  = new("Железо просканировано", "Залізо проскановано", "Hardware scanned"),
        ["dash.diag"]     = new("Диагноз", "Діагноз", "Diagnosis"),
        ["dash.optimize"] = new("Оптимизировать", "Оптимізувати", "Optimize"),
        ["dash.scan"]     = new("Сканировать заново", "Сканувати знову", "Re-scan"),

        ["spec.cpu"]      = new("Процессор", "Процесор", "CPU"),
        ["spec.gpu"]      = new("Видеокарта", "Відеокарта", "GPU"),
        ["spec.ram"]      = new("Память", "Пам'ять", "RAM"),
        ["spec.mon"]      = new("Монитор", "Монітор", "Monitor"),
        ["note.cpu.limit"]= new("главный лимит", "головний ліміт", "main limit"),
        ["note.gpu.ok"]   = new("есть запас", "є запас", "headroom left"),
        ["note.ram.mixed"]= new("разнокалиберный набор — узкое место", "різнокаліберний набір — вузьке місце", "mismatched kit — bottleneck"),
        ["note.ram.ok"]   = new("норма", "норма", "ok"),
        ["note.ram.single"]= new("одноканал — узкое место", "одноканал — вузьке місце", "single-channel — bottleneck"),
        ["note.gpu.igpu"] = new("встройка — потолок FPS", "вбудована — стеля FPS", "iGPU — FPS ceiling"),
        ["note.mon.high"] = new("высокая частота — хорошо для CS2", "висока частота — добре для CS2", "high refresh — great for CS2"),
        ["note.mon.mid"]  = new("средняя частота", "середня частота", "mid refresh rate"),
        ["note.mon.low"]  = new("низкая частота — потолок плавности", "низька частота — стеля плавності", "low refresh — smoothness ceiling"),
        ["ram.single"]    = new("1 планка", "1 планка", "1 stick"),
        ["ram.dual"]      = new("двухканал", "двоканал", "dual-channel"),
        ["findings.hdr"]  = new("Что можно улучшить", "Що можна покращити", "What you can improve"),

        ["boostmode.title"] = new("Игровой фокус", "Ігровий фокус", "Game Focus"),
        ["boostmode.desc"]  = new("Замораживает лишний фон (браузер, облачные синхронизации, апдейтеры) и чистит память на время игры. Голосовые чаты (Discord и т.п.), музыку и Steam НЕ трогает. Освобождает ядра CPU — выше 1% low, меньше статтера. Всё вернётся, когда выключишь.",
                                  "Заморожує зайвий фон (браузер, хмарні синхронізації, апдейтери) і чистить пам'ять на час гри. Голосові чати (Discord тощо), музику та Steam НЕ чіпає. Звільняє ядра CPU — вищий 1% low, менше статтеру. Усе повернеться, коли вимкнеш.",
                                  "Freezes needless background apps (browser, cloud sync, updaters) and frees memory while you play. Leaves voice chats (Discord etc.), music and Steam alone. Frees CPU cores — higher 1% lows, less stutter. Everything comes back when you turn it off."),
        ["boostmode.on"]    = new("Фон усыплён: {0} прил. Ядра и память освобождены.", "Фон приспано: {0} дод. Ядра і пам'ять звільнені.", "Background suspended: {0} apps. Cores and memory freed."),
        ["boostmode.off"]   = new("Фон разбужен ({0} прил.). Всё вернулось к обычному режиму.", "Фон розбуджено ({0} дод.). Усе повернулось.", "Background resumed ({0} apps). Back to normal."),
        ["boostmode.none"]  = new("Подходящих фоновых приложений не найдено — усыплять нечего.", "Відповідних фонових додатків не знайдено.", "No matching background apps found — nothing to suspend."),
        ["boostmode.active"] = new("Режим активен: фон усыплён. Выключи, чтобы разбудить.", "Режим активний: фон приспано. Вимкни, щоб розбудити.", "Active: background suspended. Turn off to resume."),

        ["nav.settings"]     = new("Настройки", "Налаштування", "Settings"),
        ["settings.title"]   = new("Настройки", "Налаштування", "Settings"),
        ["settings.sub"]     = new("Автоматизация: пусть Source2Boost сам держит оптимизацию и включает игровой режим при старте CS2.",
                                   "Автоматизація: хай Source2Boost сам тримає оптимізацію й вмикає ігровий режим при старті CS2.",
                                   "Automation: let Source2Boost keep the optimization enforced and switch on game mode when CS2 starts."),
        ["auto.start.title"] = new("Запускать с Windows", "Запускати з Windows", "Start with Windows"),
        ["auto.start.desc"]  = new("Тихо стартует при входе (свёрнутым), чтобы следить за запуском CS2.",
                                   "Тихо стартує при вході (згорнутим), щоб стежити за запуском CS2.",
                                   "Starts quietly at login (minimized) to watch for CS2 launching."),
        ["auto.start.err"]   = new("Не удалось изменить автозапуск (нужны права администратора).", "Не вдалося змінити автозапуск.", "Couldn't change autostart (admin rights needed)."),
        ["auto.game.title"]  = new("Авто-режим при старте CS2", "Авто-режим при старті CS2", "Auto mode when CS2 starts"),
        ["auto.game.desc"]   = new("Когда запускаешь CS2: включает Игровой фокус и заново применяет твики, которые Windows могла сбросить (службы). После выхода из игры всё возвращает.",
                                   "Коли запускаєш CS2: вмикає Ігровий фокус і заново застосовує твіки, які Windows могла скинути (служби). Після виходу з гри все повертає.",
                                   "When you launch CS2: enables Game Focus and re-applies tweaks Windows may have reset (services). Reverts everything after you quit."),

        ["tweaks.revertall.confirm"] = new("Откатить все применённые твики и вернуть настройки Windows как было? Это отменит всю оптимизацию.",
                                   "Відкотити всі застосовані твіки й повернути налаштування Windows як було? Це скасує всю оптимізацію.",
                                   "Revert every applied tweak and restore the original Windows settings? This undoes all optimization."),
        ["dlg.yes"]          = new("Да", "Так", "Yes"),
        ["dlg.no"]           = new("Отмена", "Скасувати", "Cancel"),
        ["error.title"]      = new("Что-то пошло не так", "Щось пішло не так", "Something went wrong"),
        ["error.body"]       = new("Код ошибки: {0}\n\nПришли этот код разработчику — по нему в журнале найдутся все подробности.\n\nЧто произошло: {1}\n\nЖурнал: {2}",
                                   "Код помилки: {0}\n\nНадішли цей код розробнику — за ним у журналі знайдуться всі подробиці.\n\nЩо сталося: {1}\n\nЖурнал: {2}",
                                   "Error code: {0}\n\nSend this code to the developer — it locates the full details in the log.\n\nWhat happened: {1}\n\nLog: {2}"),
        ["error.crash"]      = new("Source2Boost столкнулся с ошибкой, но продолжит работу.\n\nКод ошибки: {0}\n\nПришли этот код разработчику — по нему в журнале найдутся подробности. Если приложение ведёт себя странно, перезапусти его.\n\nЖурнал: {1}",
                                   "Source2Boost зіткнувся з помилкою, але продовжить роботу.\n\nКод помилки: {0}\n\nНадішли цей код розробнику — за ним у журналі знайдуться подробиці. Якщо застосунок поводиться дивно, перезапусти його.\n\nЖурнал: {1}",
                                   "Source2Boost hit an error but will keep running.\n\nError code: {0}\n\nSend this code to the developer — it locates the details in the log. If the app behaves oddly, restart it.\n\nLog: {1}"),

        ["update.title"]     = new("Обновления", "Оновлення", "Updates"),
        ["update.version"]   = new("Версия", "Версія", "Version"),
        ["update.hint"]      = new("Нажми «Проверить», чтобы узнать, есть ли новая версия.",
                                   "Натисни «Перевірити», щоб дізнатися, чи є нова версія.",
                                   "Click «Check» to see if a new version is available."),
        ["update.check"]     = new("Проверить", "Перевірити", "Check"),
        ["update.checking"]  = new("Проверяю обновления…", "Перевіряю оновлення…", "Checking for updates…"),
        ["update.uptodate"]  = new("У тебя последняя версия.", "У тебе остання версія.", "You're on the latest version."),
        ["update.available"] = new("Доступна версия {0}.", "Доступна версія {0}.", "Version {0} is available."),
        ["update.confirm"]   = new("Скачать и установить версию {0}? Приложение закроется, чтобы установщик обновил файлы.",
                                   "Завантажити й встановити версію {0}? Застосунок закриється, щоб інсталятор оновив файли.",
                                   "Download and install version {0}? The app will close so the installer can update files."),
        ["update.downloading"] = new("Скачиваю… {0}%", "Завантажую… {0}%", "Downloading… {0}%"),
        ["update.error"]     = new("Не удалось проверить обновления (проверь интернет).",
                                   "Не вдалося перевірити оновлення (перевір інтернет).",
                                   "Couldn't check for updates (check your connection)."),
        ["welcome.sub"]   = new("Начнём со сканирования системы: найдём слабые места, подберём план оптимизации и покажем, что стоит сделать вручную.",
                                "Почнемо зі сканування системи: знайдемо слабкі місця, підберемо план оптимізації та покажемо, що варто зробити вручну.",
                                "Let's start by scanning your system: we'll find weak spots, pick an optimization plan and show what's worth doing manually."),
        ["welcome.scan"]  = new("Сканировать систему", "Сканувати систему", "Scan system"),
        ["welcome.scanning"] = new("Сканирую систему…", "Скануюю систему…", "Scanning system…"),
        ["loading"]       = new("Загрузка…", "Завантаження…", "Loading…"),

        ["tweaks.title"]  = new("Твики вручную", "Твіки вручну", "Manual tweaks"),
        ["tweaks.sub"]    = new("Включай по одному. У каждого — риск и ожидаемый эффект.",
                                "Вмикай по одному. У кожного — ризик та очікуваний ефект.",
                                "Toggle them one by one. Each shows risk and expected impact."),

        ["lab.title"]     = new("Лаборатория", "Лабораторія", "Lab"),
        ["lab.sub"]       = new("Экспериментальные твики: работают и полностью обратимы, но польза НЕ доказана. Не входят в профили и в оценку. Включи один → перезагрузка → прогони «Авто-замер» в разделе «Тест и прогноз» до/после. Оставляй только то, что реально помогло.",
                                "Експериментальні твіки: працюють і повністю оборотні, але користь НЕ доведена. Не входять у профілі та в оцінку. Увімкни один → перезавантаження → прожени «Авто-замір» у розділі «Тест і прогноз» до/після. Залишай лише те, що реально допомогло.",
                                "Experimental tweaks: they work and are fully reversible, but the benefit is UNPROVEN. Excluded from profiles and the score. Enable one → reboot → run Auto-benchmark in Test & forecast before/after. Keep only what actually helped."),
        ["lab.bench.title"] = new("Проверяй замером, а не на глаз", "Перевіряй виміром, а не на око", "Prove it by measuring, not by feel"),
        ["lab.bench.body"] = new("В разделе «Тест и прогноз» кнопка «Авто-замер» прогоняет бенч-карту и показывает средний FPS, 1% low и сравнение с «до» — по ним и видно эффект.",
                                 "У розділі «Тест і прогноз» кнопка «Авто-замір» проганяє бенч-карту й показує середній FPS, 1% low і порівняння з «до» — за ними й видно ефект.",
                                 "In Test & forecast, the Auto-benchmark button runs the benchmark map and shows average FPS, 1% low and the vs-before comparison — that's where the effect shows."),
        ["lab.tomonitor"] = new("Открыть замер", "Відкрити вимір", "Open benchmark"),
        ["lab.empty"]     = new("Под ваше железо пока нет экспериментальных твиков.",
                                "Під ваше залізо поки немає експериментальних твіків.",
                                "No experimental tweaks for your hardware yet."),

        ["boost.title"]   = new("Оптимизация в один клик", "Оптимізація в один клік", "One-click optimization"),
        ["boost.stub"]    = new("Скоро: профили Safe / Максимум / Бенчмарк.", "Скоро: профілі Safe / Максимум / Бенчмарк.", "Coming soon: Safe / Maximum / Benchmark profiles."),
        ["boost.sub"]     = new("Выбери профиль. Всё обратимо, перед применением создаётся точка восстановления.",
                                "Обери профіль. Усе оборотно, перед застосуванням створюється точка відновлення.",
                                "Pick a profile. Everything is reversible; a restore point is created first."),
        ["profile.safe"]    = new("Безопасный", "Безпечний", "Safe"),
        ["profile.optimal"] = new("Оптимальный", "Оптимальний", "Optimal"),
        ["profile.max"]     = new("Максимум", "Максимум", "Maximum"),
        ["profile.recommended"] = new("рекомендуется", "рекомендується", "recommended"),
        ["hw.diag.title"] = new("Рекомендуем профиль «{0}» — под ваше железо", "Рекомендуємо профіль «{0}» — під ваше залізо", "We recommend the \"{0}\" profile — for your hardware"),
        ["profile.apply"]   = new("Применить", "Застосувати", "Apply"),
        ["profile.safe.desc"]    = new("Только безопасные твики (риск 0). Без перезагрузки, мгновенно обратимо. {0}.",
                                       "Лише безпечні твіки (ризик 0). Без перезавантаження, миттєво оборотно. {0}.",
                                       "Safe tweaks only (zero risk). No reboot, instantly reversible. {0}."),
        ["profile.optimal.desc"] = new("Баланс прироста и безопасности: безопасные + средние. Подходит большинству. {0}.",
                                       "Баланс приросту й безпеки: безпечні + середні. Підходить більшості. {0}.",
                                       "Balance of gains and safety: safe + medium. Best for most. {0}."),
        ["profile.max.desc"]     = new("Всё, включая агрессивное (Spectre off, таймеры загрузчика, Nagle). Максимум FPS, снижаются часть защит. {0}.",
                                       "Усе, включно з агресивним (Spectre off, таймери завантажувача, Nagle). Максимум FPS, знижуються частина захистів. {0}.",
                                       "Everything, including aggressive (Spectre off, boot timers, Nagle). Max FPS, lowers some protections. {0}."),
        ["monitor.title"] = new("Мониторинг фреймтайма", "Моніторинг фреймтайму", "Frametime monitor"),
        ["monitor.stub"]  = new("Скоро: живой график FPS/фреймтайма через PresentMon.", "Скоро: живий графік FPS/фреймтайму через PresentMon.", "Coming soon: live FPS/frametime graph via PresentMon."),
        ["cs2.title"]     = new("Настройки CS2", "Налаштування CS2", "CS2 config"),
        ["cs2.stub"]      = new("Скоро: генерация autoexec.cfg и параметров запуска.", "Скоро: генерація autoexec.cfg та параметрів запуску.", "Coming soon: autoexec.cfg and launch options."),

        ["monitor.sub"]     = new("Замер реального фреймтайма cs2.exe через PresentMon.", "Замір реального фреймтайму cs2.exe через PresentMon.", "Measure cs2.exe real frametime via PresentMon."),
        ["monitor.hint"]    = new("Замер полу-автоматический: программа запускает CS2 с нужными флагами, ты один раз выбираешь карту-бенчмарк в Мастерской (любую, чей итог идёт в консоль), а результат и сравнение «до/после» программа ловит сама. Одна карта = один и тот же сценарий каждый раз.",
                                  "Замір напів-автоматичний: програма запускає CS2 з потрібними прапорцями, ти один раз обираєш карту-бенчмарк у Майстерні (будь-яку, чий підсумок іде в консоль), а результат і порівняння «до/після» програма ловить сама.",
                                  "Semi-automatic: the app launches CS2 with the right flags, you pick a benchmark map in the Workshop once (any map that prints its result to the console), and the app captures the result and before/after comparison itself."),
        ["monitor.measure"] = new("Замерить (60 сек)", "Заміряти (60 с)", "Measure (60s)"),
        ["monitor.working"] = new("Замеряю 60 секунд… играй активно.", "Замірюю 60 секунд… грай активно.", "Measuring 60s… play actively."),
        ["monitor.nocs2"]   = new("Сначала запусти CS2 и зайди на карту, потом жми «Замерить».", "Спершу запусти CS2 і зайди на карту, потім тисни «Заміряти».", "Launch CS2 and load a map first, then hit Measure."),
        ["monitor.countdown"] = new("Замеряю… осталось {0} сек. Играй активно (двигайся, стреляй).", "Замірюю… залишилось {0} с. Грай активно (рухайся, стріляй).", "Measuring… {0}s left. Play actively (move, shoot)."),
        ["monitor.result"]  = new("Средний FPS: {0}\n1% low: {1}\n0.1% low: {2}\nМакс. статтер: {3} мс\nРазброс фреймтайма: {4}\nКадров: {5}",
                                  "Середній FPS: {0}\n1% low: {1}\n0.1% low: {2}\nМакс. статтер: {3} мс\nРозкид фреймтайму: {4}\nКадрів: {5}",
                                  "Average FPS: {0}\n1% low: {1}\n0.1% low: {2}\nMax stutter: {3} ms\nFrametime spread: {4}\nFrames: {5}"),
        ["monitor.baseline.set"] = new("Запомнить как «до»", "Запам'ятати як «до»", "Save as \"before\""),
        ["monitor.baseline.none"] = new("Эталон «до» не задан. Замерь до применения твика и нажми «Запомнить как до».",
                                        "Еталон «до» не задано. Зміряй до застосування твіка й натисни «Запам'ятати як до».",
                                        "No \"before\" baseline yet. Measure before applying a tweak, then hit \"Save as before\"."),
        ["monitor.baseline.cur"] = new("Эталон «до»: {0}", "Еталон «до»: {0}", "Baseline \"before\": {0}"),
        ["monitor.delta.title"] = new("Сравнение с «до» (▲ = лучше)", "Порівняння з «до» (▲ = краще)", "Vs \"before\" (▲ = better)"),
        ["monitor.auto.btn"] = new("Авто-замер (бенч-карта)", "Авто-замір (бенч-карта)", "Auto-benchmark (map)"),
        ["monitor.auto.hint"] = new("CS2 должен быть закрыт — программа сама запустит его с -condebug и fps_max 0. Дальше в игре: Играть → Мастерская → карта-бенчмарк → Go. Подойдёт ЛЮБАЯ карта, выводящая итог в консоль (Avg / P1). Поле ниже — только чтобы быстро подписаться на рекомендованную карту (необязательно).",
                                    "CS2 має бути закритий — програма сама запустить його з -condebug і fps_max 0. Далі в грі: Грати → Майстерня → карта-бенчмарк → Go. Підійде БУДЬ-ЯКА карта, що виводить підсумок у консоль (Avg / P1). Поле нижче — лише щоб швидко підписатися на рекомендовану карту (необов'язково).",
                                    "CS2 must be closed — the app launches it with -condebug and fps_max 0. Then in-game: Play → Workshop → benchmark map → Go. ANY map that prints its result to the console (Avg / P1) works. The field below just helps you subscribe to a recommended map (optional)."),
        ["monitor.auto.title"] = new("Авто-замер (бенч-карта)", "Авто-замір (бенч-карта)", "Auto-benchmark (map)"),
        ["monitor.benchmap.label"] = new("Рекомендуемая карта (необязательно):", "Рекомендована карта (необов'язково):", "Recommended map (optional):"),
        ["monitor.subscribe"] = new("Открыть карту (подписаться)", "Відкрити карту (підписатися)", "Open map (subscribe)"),
        ["monitor.auto.badid"] = new("Укажи корректный ID карты из мастерской (только цифры).", "Вкажи коректний ID карти з майстерні (лише цифри).", "Enter a valid workshop map ID (digits only)."),
        ["monitor.auto.subscribe"] = new("Карта ещё не подписана в мастерской — без этого Steam не даст её загрузить (подписка разовая). Открыть страницу карты, чтобы подписаться? После подписки просто нажми «Авто-замер» снова.",
                                         "Карта ще не підписана в майстерні — без цього Steam не дасть її завантажити (підписка разова). Відкрити сторінку карти, щоб підписатися? Після підписки просто натисни «Авто-замір» знову.",
                                         "The map isn't subscribed in the Workshop yet — Steam won't load it otherwise (one-time subscribe). Open the map page to subscribe? After subscribing, just hit Auto-benchmark again."),
        ["monitor.auto.running"] = new("CS2 уже запущен. Закрой игру — авто-замер сам запустит её с нужными флагами (-condebug), потом выберешь карту в Мастерской.",
                                       "CS2 вже запущений. Закрий гру — авто-замір сам запустить її з потрібними прапорцями (-condebug), потім обереш карту в Майстерні.",
                                       "CS2 is already running. Close it — auto-benchmark will relaunch it with the right flags (-condebug), then pick a map in the Workshop."),
        ["monitor.auto.loading"] = new("Запускаю CS2…", "Запускаю CS2…", "Launching CS2…"),
        ["monitor.auto.waiting"] = new("CS2 запущена. Открой Играть → Мастерская → карта-бенчмарк → Go. Ловлю результат из консоли… {0} сек.",
                                       "CS2 запущена. Відкрий Грати → Майстерня → карта-бенчмарк → Go. Ловлю результат із консолі… {0} с.",
                                       "CS2 is up. Open Play → Workshop → benchmark map → Go. Catching the result from the console… {0}s."),
        ["monitor.auto.timeout"] = new("Не дождались итога бенчмарка. Запусти карту-бенчмарк в Мастерской (Играть → Мастерская → карта → Go) и дождись конца прогона — итог печатается в конце. Карта должна выводить результат в консоль (Avg / P1).",
                                       "Не дочекалися підсумку бенчмарку. Запусти карту-бенчмарк у Майстерні (Грати → Майстерня → карта → Go) і дочекайся кінця прогону — підсумок друкується в кінці.",
                                       "Didn't get a benchmark result. Start a benchmark map in the Workshop (Play → Workshop → map → Go) and wait for the run to finish — the result prints at the end. The map must print its result to the console (Avg / P1)."),
        ["monitor.auto.result"] = new("Бенчмарк карты: средний FPS {0}, 1% low {1}", "Бенчмарк карти: середній FPS {0}, 1% low {1}", "Map benchmark: average FPS {0}, 1% low {1}"),
        ["monitor.auto.nodemo"] = new("Эталонная демка не найдена. Запиши её ОДИН раз: зайди в дефматч на de_dust2, в консоли набери record s2b_bench, поиграй ~60 сек активно (движение, стрельба, смоки), затем stop. Файл s2b_bench.dem положи в папку replays (открою её сейчас). После этого «Авто-замер» будет прогонять ровно эту сцену каждый раз. Открыть папку replays?",
                                     "Еталонну демку не знайдено. Запиши її ОДИН раз: зайди в дефматч на de_dust2, у консолі набери record s2b_bench, пограй ~60 с активно (рух, стрільба, смоки), потім stop. Файл s2b_bench.dem поклади в папку replays (відкрию її зараз). Після цього «Авто-замір» проганятиме саме цю сцену щоразу. Відкрити папку replays?",
                                     "No reference demo found. Record it ONCE: join a deathmatch on de_dust2, type record s2b_bench in console, play ~60s actively (move, shoot, smokes), then stop. Put s2b_bench.dem into the replays folder (I'll open it now). After that, Auto-benchmark replays exactly that scene every time. Open the replays folder?"),
        ["monitor.auto.launching"] = new("Запускаю CS2…", "Запускаю CS2…", "Launching CS2…"),
        ["monitor.auto.launchfail"] = new("Не удалось запустить CS2. Запусти игру вручную (с параметром запуска -condebug) и попробуй снова.", "Не вдалося запустити CS2. Запусти гру вручну (з параметром -condebug) та спробуй знову.", "Couldn't launch CS2. Start the game manually (with the -condebug launch option) and try again."),

        ["cs2.sub"]         = new("Параметры запуска Steam и autoexec.cfg для максимума FPS.", "Параметри запуску Steam та autoexec.cfg для максимуму FPS.", "Steam launch options and autoexec.cfg for max FPS."),
        ["cs2.path"]        = new("Установка CS2", "Встановлення CS2", "CS2 install"),
        ["cs2.launch"]      = new("Параметры запуска", "Параметри запуску", "Launch options"),
        ["cs2.copy"]        = new("Копировать", "Копіювати", "Copy"),
        ["cs2.copied"]      = new("Скопировано ✓", "Скопійовано ✓", "Copied ✓"),
        ["cs2.instr"]       = new("Вставь в Steam: ПКМ по CS2 → Свойства → Параметры запуска.", "Встав у Steam: ПКМ по CS2 → Властивості → Параметри запуску.", "Paste in Steam: right-click CS2 → Properties → Launch Options."),
        ["cs2.autoexec"]    = new("autoexec.cfg", "autoexec.cfg", "autoexec.cfg"),
        ["cs2.install"]     = new("Установить autoexec.cfg", "Встановити autoexec.cfg", "Install autoexec.cfg"),
        ["cs2.notfound"]    = new("CS2 не найден (установлен ли CS2 и запускался ли Steam?)", "CS2 не знайдено (чи встановлено CS2 і чи запускався Steam?)", "CS2 not found (is it installed and has Steam run?)"),
        ["cs2.installed"]   = new("Установлен: {0}", "Встановлено: {0}", "Installed: {0}"),
        ["cs2.notinstalled"]= new("Не установлен. Нажми кнопку ниже.", "Не встановлено. Натисни кнопку нижче.", "Not installed. Click the button below."),
        ["cs2.install.ok"]  = new("autoexec.cfg записан:\n{0}\n\nПараметры запуска (кнопка «Копировать» выше) уже включают +exec autoexec.",
                                  "autoexec.cfg записано:\n{0}\n\nПараметри запуску (кнопка «Копіювати» вище) вже містять +exec autoexec.",
                                  "autoexec.cfg written:\n{0}\n\nThe launch options (Copy button above) already include +exec autoexec."),
        ["cs2.video.title"] = new("Игровой конфиг графики (макс. FPS)", "Ігровий конфіг графіки (макс. FPS)", "In-game graphics config (max FPS)"),
        ["cs2.video.desc"]  = new("Ставит настройки графики CS2 на competitive-low (тени/эффекты/шейдеры low, MSAA и VSync off) — самый крупный игровой рычаг FPS. Разрешение не трогаем. Полностью обратимо.",
                                  "Ставить налаштування графіки CS2 на competitive-low (тіні/ефекти/шейдери low, MSAA та VSync off) — найбільший ігровий важіль FPS. Роздільність не чіпаємо. Повністю оборотно.",
                                  "Sets CS2 graphics to competitive-low (shadows/effects/shaders low, MSAA and VSync off) — the biggest in-game FPS lever. Resolution untouched. Fully reversible."),
        ["cs2.video.warn"]  = new("⚠ Закрой CS2 перед применением — иначе игра перезапишет изменения при выходе.",
                                  "⚠ Закрий CS2 перед застосуванням — інакше гра перезапише зміни при виході.",
                                  "⚠ Close CS2 before applying — otherwise the game overwrites the changes on exit."),
        ["cs2.video.apply"] = new("Применить макс. FPS", "Застосувати макс. FPS", "Apply max FPS"),
        ["cs2.video.restore"] = new("Вернуть мои настройки", "Повернути мої налаштування", "Restore my settings"),
        ["cs2.shader.title"] = new("Ремонт битого кэша шейдеров", "Ремонт битого кешу шейдерів", "Repair broken shader cache"),
        ["cs2.shader.desc"] = new("⚠️ Это НЕ рутинный буст FPS, а разовый ремонт. Применяй, ТОЛЬКО если дёргания появились после обновления игры/драйвера — тогда причиной может быть повреждённый кэш шейдеров. Чистка обратима, но кэш пересобирается: первые 1–2 матча будет заметная догрузка и микрофризы компиляции, потом ровно. Без причины не трогай.",
                                  "⚠️ Це НЕ рутинний буст FPS, а разовий ремонт. Застосовуй, ТІЛЬКИ якщо смикання з'явились після оновлення гри/драйвера — тоді причиною може бути пошкоджений кеш шейдерів. Чистка оборотна, але кеш пересобереться: перші 1–2 матчі буде помітна догрузка й мікрофризи компіляції, потім рівно. Без причини не чіпай.",
                                  "⚠️ This is NOT a routine FPS boost — it's a one-off repair. Use it ONLY if stutter appeared after a game/driver update, when a corrupted shader cache may be the cause. The cleanup is reversible, but the cache rebuilds: expect noticeable loading and compile micro-stutter for the first 1–2 matches, then smooth. Don't touch it without a reason."),
        ["cs2.shader.btn"]  = new("Сбросить кэш шейдеров", "Скинути кеш шейдерів", "Reset shader cache"),
        ["cs2.shader.cleaning"] = new("Чищу кэш шейдеров…", "Чищу кеш шейдерів…", "Clearing shader cache…"),
        ["cs2.shader.done"] = new("✓ Кэш шейдеров сброшен. При следующем запуске CS2 пересоберёт их — первые минуты возможна догрузка, потом ровнее.",
                                  "✓ Кеш шейдерів скинуто. При наступному запуску CS2 пересобере їх.",
                                  "✓ Shader cache reset. CS2 will rebuild it on next launch — some loading at first, then smoother."),
        ["cs2.video.nofile"] = new("cs2_video.txt не найден — запусти CS2 хотя бы раз, чтобы игра его создала.",
                                   "cs2_video.txt не знайдено — запусти CS2 хоча б раз.",
                                   "cs2_video.txt not found — launch CS2 once so the game creates it."),
        ["cs2.video.applied"] = new("✓ Применён конфиг макс. FPS. Запусти CS2 — настройки уже низкие.",
                                    "✓ Застосовано конфіг макс. FPS. Запусти CS2.",
                                    "✓ Max-FPS config applied. Launch CS2 — settings are already low."),
        ["cs2.video.ok"]    = new("Готово! Настройки графики CS2 выставлены на макс. FPS. Запускай игру.\n\nНе понравится — жми «Вернуть мои настройки».",
                                  "Готово! Налаштування графіки CS2 виставлені на макс. FPS. Запускай гру.\n\nНе сподобається — тисни «Повернути мої налаштування».",
                                  "Done! CS2 graphics set to max FPS. Launch the game.\n\nDon't like it? Hit 'Restore my settings'."),
        ["cs2.video.restored"] = new("Твои прежние настройки графики восстановлены.", "Твої попередні налаштування графіки відновлено.", "Your previous graphics settings are restored."),
        ["cs2.video.err.running"] = new("Сначала полностью закрой CS2 — она перезапишет файл при выходе.",
                                        "Спершу повністю закрий CS2 — вона перезапише файл при виході.",
                                        "Close CS2 completely first — it overwrites the file on exit."),
        ["cs2.video.err.nofile"] = new("cs2_video.txt не найден. Запусти CS2 хотя бы раз.", "cs2_video.txt не знайдено. Запусти CS2 хоча б раз.", "cs2_video.txt not found. Launch CS2 once."),
        ["cs2.video.err.generic"] = new("Не удалось изменить конфиг графики. Подробности в логе.", "Не вдалося змінити конфіг графіки. Деталі в лозі.", "Couldn't change the graphics config. See the log."),

        ["restore.title"] = new("Откат изменений", "Відкат змін", "Restore changes"),
        ["restore.stub"]  = new("Скоро: список снимков и откат в один клик.", "Скоро: список знімків і відкат в один клік.", "Coming soon: snapshots list and one-click revert."),
        ["restore.sub"]   = new("Применённые твики. Откати любой по отдельности или все сразу.", "Застосовані твіки. Відкоти будь-який окремо або всі одразу.", "Applied tweaks. Revert any one, or all at once."),
        ["restore.empty"] = new("Пока ничего не применено.", "Поки нічого не застосовано.", "Nothing applied yet."),
        ["restore.refresh"] = new("Обновить", "Оновити", "Refresh"),
        ["restore.revert"] = new("Откатить", "Відкотити", "Revert"),
        ["restore.reboot"] = new("· нужна перезагрузка", "· потрібне перезавантаження", "· needs reboot"),
        ["restore.note"]  = new("Бэкапы реестра и точка восстановления Windows создаются автоматически перед изменениями.",
                                "Бекапи реєстру та точка відновлення Windows створюються автоматично перед змінами.",
                                "Registry backups and a Windows restore point are created automatically before changes."),

        ["risk.safe"]     = new("риск 0", "ризик 0", "zero risk"),
        ["risk.medium"]   = new("средний", "середній", "medium"),
        ["risk.high"]     = new("агрессивно", "агресивно", "aggressive"),
        ["risk.extreme"]  = new("безбашенно", "безбашенно", "unhinged"),
        ["risk.soon"]     = new("скоро", "скоро", "soon"),
        ["risk.experimental"] = new("эксперимент", "експеримент", "experimental"),

        ["theme"]         = new("Тема", "Тема", "Theme"),
        ["opt.title"]     = new("Оптимизация", "Оптимізація", "Optimization"),
        ["opt.confirm"]   = new("Применить профиль «{0}» ({1})?\nПеред применением создаётся точка восстановления Windows.",
                                "Застосувати профіль «{0}» ({1})?\nПеред застосуванням створюється точка відновлення Windows.",
                                "Apply the “{0}” profile ({1})?\nA Windows restore point is created first."),
        ["opt.reboot"]    = new("\n⚠ Часть изменений вступит в силу только после перезагрузки.",
                                "\n⚠ Частина змін набуде чинності лише після перезавантаження.",
                                "\n⚠ Some changes take effect only after a restart."),
        ["profile.reboot"] = new("⚠ нужна перезагрузка", "⚠ потрібне перезавантаження", "⚠ needs a restart"),
        ["profile.active"] = new("Активно", "Активно", "Active"),

        ["nav.bios"]      = new("BIOS", "BIOS", "BIOS"),

        // Тест: оценка + прогноз FPS
        ["test.title"]    = new("Тест и прогноз", "Тест і прогноз", "Test & forecast"),
        ["test.sub"]      = new("Оценка оптимизации, прогноз FPS и реальный замер фреймтайма cs2.exe.",
                                "Оцінка оптимізації, прогноз FPS та реальний замір фреймтайму cs2.exe.",
                                "Optimization score, FPS forecast and a real cs2.exe frametime measurement."),
        ["score.title"]   = new("Оценка оптимизации", "Оцінка оптимізації", "Optimization score"),
        ["score.sub"]     = new("Применено {0} из {1}. Чем выше — тем полнее реализован потенциал твиков.",
                                "Застосовано {0} з {1}. Чим вище — тим повніше реалізовано потенціал твіків.",
                                "Applied {0} of {1}. Higher means more of the tweak potential is realized."),
        ["forecast.title"] = new("Прогноз среднего FPS в CS2", "Прогноз середнього FPS у CS2", "CS2 average FPS forecast"),
        ["forecast.line"]  = new("Сейчас ~{0} → потенциал ~{1} (с настройкой BIOS ~{2})",
                                 "Зараз ~{0} → потенціал ~{1} (з налаштуванням BIOS ~{2})",
                                 "Now ~{0} → potential ~{1} (with BIOS tuning ~{2})"),
        ["forecast.measured"] = new("на основе твоего замера", "на основі твого заміру", "based on your measurement"),
        ["forecast.estimate"] = new("грубая оценка по железу — сделай замер для точности",
                                    "груба оцінка за залізом — зроби замір для точності",
                                    "rough hardware estimate — run a measurement for accuracy"),
        ["cs2.fps.label"] = new("Лимит FPS (fps_max в autoexec)", "Ліміт FPS (fps_max в autoexec)", "FPS cap (fps_max in autoexec)"),
        ["cs2.fps.hint"]  = new("Ставь у стабильного потолка = средний FPS после теста или чуть ниже: ровнее фреймтайм. 0 = без лимита. Рекомендуем: {0}.",
                                "Став біля стабільної стелі = середній FPS після тесту або трохи нижче: рівніший фреймтайм. 0 = без ліміту. Рекомендуємо: {0}.",
                                "Set it at your stable ceiling = average FPS after testing or slightly below: steadier frametime. 0 = unlimited. Suggested: {0}."),
        ["cs2.fps.hint.low1"] = new("Рассчитано от твоего измеренного 1% low — кап чуть ниже него держит фреймтайм максимально ровным (средний FPS слегка подрежется ради плавности). 0 = без лимита. Рекомендуем: {0}.",
                                    "Розраховано від твого виміряного 1% low — кап трохи нижче нього тримає фреймтайм максимально рівним (середній FPS трохи підріжеться заради плавності). 0 = без ліміту. Рекомендуємо: {0}.",
                                    "Computed from your measured 1% low — a cap just below it keeps frametime as flat as possible (average FPS is trimmed a bit for smoothness). 0 = unlimited. Suggested: {0}."),
        ["bios.title"]    = new("Настройка BIOS/UEFI", "Налаштування BIOS/UEFI", "BIOS/UEFI setup"),
        ["bios.sub"]      = new("Рекомендации под твоё железо. BIOS программа не меняет — эти шаги нужно сделать вручную при загрузке (обычно Del/F2).",
                                "Рекомендації під твоє залізо. BIOS програма не змінює — ці кроки треба зробити вручну під час завантаження (зазвичай Del/F2).",
                                "Recommendations for your hardware. The app can't change BIOS — do these manually at boot (usually Del/F2)."),
        ["bios.level.rec"] = new("рекомендуется", "рекомендується", "recommended"),
        ["bios.level.opt"] = new("по желанию", "за бажанням", "optional"),
        ["bios.level.warn"] = new("важно", "важливо", "important"),
        ["opt.working"]   = new("Применяю…", "Застосовую…", "Applying…"),
        ["opt.done"]      = new("Готово: применено {0} из {1}.\nОткатить можно на вкладке «Откат» или кнопкой «Откатить всё».",
                                "Готово: застосовано {0} з {1}.\nВідкотити можна на вкладці «Відкат» або кнопкою «Відкотити все».",
                                "Done: {0} of {1} applied.\nRevert via the Restore tab or the “Revert all” button."),
        ["tweaks.apply"]  = new("Применить выбранные", "Застосувати вибрані", "Apply selected"),
        ["tweaks.revertall"] = new("Откатить всё", "Відкотити все", "Revert all"),
        ["tweaks.result"] = new("Применено: {0} · Пропущено: {1}", "Застосовано: {0} · Пропущено: {1}", "Applied: {0} · Skipped: {1}"),
        ["tweaks.reverted"] = new("Откат выполнен: {0}", "Відкат виконано: {0}", "Reverted: {0}"),
        ["tweaks.reconcile"] = new("Включено: {0} · Откачено: {1}", "Увімкнено: {0} · Відкочено: {1}", "Enabled: {0} · Reverted: {1}"),
    };
}
